theme: jekyll-theme-cayman
title: JK Embedded Consulting
description: Provider of customized embedded computing solutions

social-network-links:
  github: jadonk
  twitter: jadon
  linkedin: jkridner
  calendly: jkridner
