theme: jekyll-theme-cayman
title: JK Embedded Consulting
description: Provider of customized embedded computing solutions
image: https://user-images.githubusercontent.com/9018/218166227-af75f41b-cfd8-4462-8f57-f64789c6fe5d.png

social-network-links:
  github: jadonk
  twitter: jadon
  linkedin: jkridner
  calendly: jkridner
